### PR TITLE
rename rawhide branch

### PR DESCRIPTION
**Pull request by TristanCacqueray**
This change follow-up on the fedora branch project rename:
https://pagure.io/fesco/issue/2519

### CODE REVIEW

**Comment by juhp** [comment]
Thanks for this!
I was thinking to use `Rawhide` though, but I haven't digested everything yet.

**Comment by TristanCacqueray** [comment]
I first used `Rawhide` in https://github.com/juhp/fedora-dists/commit/bcb31e0ff12176e51f0747980cc4a808585563c1 , but it looked better (and easier) to simply rename to Main.

Also I think `eitherBranch` needs another matcher to handle both "main" and "rawhide"

**Comment by juhp** [comment]
Maybe I will merge that instead then if you don't mind - I believe the canonical package branch name should be `rawhide` (whereas `main` is a symref for dist-git rpms/).

**Comment by TristanCacqueray** [comment]
Ok, let me restore that commit

**Comment by juhp** [comment]
Merged, thanks again!

**Comment by juhp** [comment]
> Also I think `eitherBranch` needs another matcher to handle both "main" and "rawhide"

Good point, thanks for catching that

**Comment by juhp** [comment]
> > Also I think `eitherBranch` needs another matcher to handle both "main" and "rawhide"

Actually this seems to lead to "double-counting" of branches in fbrnch, so I may need to undo this hunk.
Otherwise I might need to think how to handle `main` better, my initial plan was just to ignore/hide it.

**Comment by TristanCacqueray** [comment]
Oops, this is confusing :-) I hope change merged to the main branch do land in the rawhide branch.

**Comment by juhp** [comment]
Yea, personally I think having both `rawhide` and `main` was a Bad Idea™...
But yes anything you push to origin/main will also be in origin/rawhide, since main is just a symref pointing to rawhide HEAD.
But locally they are separate branches for better or worse.
I think the idea was that having `main` would bring some consistency with non-dist-git repo's... but "rawhide" better reflects what the branch is.

I am still not very happy with it, since fbrnch currently treats `main` branches as "non-release", which is not ideal either.
I could imagine some Packagers might prefer to use `main` because say it is less typing... eventually I might make it a config option or something. Feedback is welcome...

**Pull request merged**
